@startuml
'https://plantuml.com/class-diagram

abstract class AbstractProp{
    + AbstractProp(int locationX, int locationY, int speedX, int speedY)
    + forward()
    + {abstract} applyToAircraft(HeroAircraft heroAircraft):void
 }

class PropBlood{
    - healing:int
    + PropBlood(int healing)
    + applyToAircraft(HeroAircraft heroAircraft):void
}

class PropBullet{
    + PropBullet()
    + applyToAircraft(HeroAircraft heroAircraft):void
}

class PropBomb{
    + PropBomb()
    + applyToAircraft(HeroAircraft heroAircraft):void
}

abstract class PropFactory{
    + PropFactory()
    + {abstract}createProp(EnemyAircraft enemyAircraft): AbstractProp
}

class PropBloodFactory{
    - int healing
    + PropBloodFactory(int healing)
    + createProp(EnemyAircraft enemyAircraft): AbstractProp
}

class PropBulletFactory{
    + PropBulletFactory()
    + createProp(EnemyAircraft enemyAircraft): AbstractProp
}

class PropBombFactory{
    + PropBombFactory()
    + createProp(EnemyAircraft enemyAircraft): AbstractProp
}

AbstractProp <|-- PropBlood
AbstractProp <|-- PropBullet
AbstractProp <|-- PropBomb
PropFactory <|-- PropBloodFactory
PropFactory <|-- PropBulletFactory
PropFactory <|-- PropBombFactory

PropFactory ..> AbstractProp
PropBloodFactory ..> PropBlood
PropBulletFactory ..> PropBullet
PropBombFactory ..> PropBomb





@enduml